import mongoose, { Document, Schema } from 'mongoose';

// ==========================================
// ENUMS
// ==========================================

export type ReviewStatus = 'pending' | 'approved' | 'rejected' | 'hidden';

// ==========================================
// SUB-INTERFACES
// ==========================================

export interface IReviewImage {
  url: string;
  publicId: string;
  isVotedByMe?: boolean;
}

export interface IHelpfulVote {
  user: mongoose.Types.ObjectId;
  votedAt: Date;
}

export interface IModerationInfo {
  status: ReviewStatus;
  moderatedBy?: mongoose.Types.ObjectId; // Admin user ID
  moderatedAt?: Date;
  reason?: string; // Reason for rejection or hiding
  autoFlags?: string[]; // Flags generated by automated moderation tools
}

// Public response from the seller
export interface ISellerReply {
  content: string;
  repliedBy: mongoose.Types.ObjectId;
  repliedAt: Date;
}

export interface IReview extends Document {
  product: mongoose.Types.ObjectId;
  user: mongoose.Types.ObjectId;
  order?: mongoose.Types.ObjectId; // Reference to purchased order for verification
  rating: number; // Rating scale 1–5
  title: string;
  content: string;
  images: IReviewImage[];
  isVerifiedPurchase: boolean; // Flag to indicate if the user actually bought the item
  moderation: IModerationInfo;
  helpfulVotes: IHelpfulVote[];
  helpfulCount: number; // Cached count for sorting performance
  notHelpfulCount: number;
  sellerReply?: ISellerReply;
  isEdited: boolean;
  editedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

// ==========================================
// SUB-SCHEMAS
// ==========================================

const ReviewImageSchema = new Schema<IReviewImage>(
  {
    url: { type: String, required: true },
    publicId: { type: String, required: true },
  },
  { _id: false }
);

const HelpfulVoteSchema = new Schema<IHelpfulVote>(
  {
    user: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    votedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

const ModerationInfoSchema = new Schema<IModerationInfo>(
  {
    status: {
      type: String,
      enum: ['pending', 'approved', 'rejected', 'hidden'],
      default: 'pending',
    },
    moderatedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    moderatedAt: Date,
    reason: { type: String, maxlength: 500 },
    autoFlags: [String],
  },
  { _id: false }
);

const SellerReplySchema = new Schema<ISellerReply>(
  {
    content: { type: String, required: true, maxlength: 1000 },
    repliedBy: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    repliedAt: { type: Date, default: Date.now },
  },
  { _id: false }
);

// ==========================================
// MAIN SCHEMA
// ==========================================

const ReviewSchema = new Schema<IReview>(
  {
    product: {
      type: Schema.Types.ObjectId,
      ref: 'Product',
      required: true,
    },
    user: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    order: {
      type: Schema.Types.ObjectId,
      ref: 'Order',
    },
    rating: {
      type: Number,
      required: [true, 'Rating is required'],
      min: [1, 'Minimum rating is 1'],
      max: [5, 'Maximum rating is 5'],
      validate: {
        validator: Number.isInteger,
        message: 'Rating must be an integer',
      },
    },
    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
      maxlength: [150, 'Title cannot exceed 150 characters'],
    },
    content: {
      type: String,
      required: [true, 'Review content is required'],
      trim: true,
      minlength: [20, 'Content must be at least 20 characters'],
      maxlength: [5000, 'Content cannot exceed 5000 characters'],
    },
    images: {
      type: [ReviewImageSchema],
      validate: {
        validator: (imgs: IReviewImage[]) => imgs.length <= 5,
        message: 'Maximum of 5 images allowed per review',
      },
    },
    isVerifiedPurchase: { type: Boolean, default: false },
    moderation: { type: ModerationInfoSchema, default: () => ({ status: 'pending' }) },
    helpfulVotes: [HelpfulVoteSchema],
    helpfulCount: { type: Number, default: 0 },
    notHelpfulCount: { type: Number, default: 0 },
    sellerReply: SellerReplySchema,
    isEdited: { type: Boolean, default: false },
    editedAt: Date,
  },
  {
    timestamps: true,
    toJSON: {
      virtuals: true,
      // Remove sensitive/large array from JSON output for performance
      transform: (_doc, ret: any) => {
        delete ret.helpfulVotes;
        return ret;
      },
    },
  }
);

// ==========================================
// INDEXES
// ==========================================

// 1. Performance: Optimize standard public listing pages
ReviewSchema.index({ product: 1, 'moderation.status': 1, createdAt: -1 });
ReviewSchema.index({ product: 1, 'moderation.status': 1, helpfulCount: -1 });
ReviewSchema.index({ product: 1, 'moderation.status': 1, rating: -1 });

// 2. User profile: Quick access to a user's own review history
ReviewSchema.index({ user: 1, createdAt: -1 });

// 3. Admin: Fast access to pending/moderation queue
ReviewSchema.index({ 'moderation.status': 1, createdAt: 1 });

// 4. UX: Prioritize reviews from verified buyers
ReviewSchema.index({ product: 1, 'moderation.status': 1, isVerifiedPurchase: -1 });

// 5. Integrity: Ensure only one review per user per product
ReviewSchema.index({ product: 1, user: 1 }, { unique: true });

// 6. Interaction: Quick check for existing "helpful" votes by a user
ReviewSchema.index({ _id: 1, 'helpfulVotes.user': 1 });

export const Review = mongoose.model<IReview>('Review', ReviewSchema);
